### ISSUE TITLE
Problem with starting server

### ISSUE THREAD

**Issue by Tim2653** [itzg/itzg#1]
I have seen many very similiar problems, but no exact copy. When I try to launch container, i see this error message:

[14:00:16]` [ServerMain/ERROR]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: t is not a recognized option
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59) ~[jopt-simple-5.0.4.jar:?]
        at joptsimple.OptionParser.parse(OptionParser.java:396) ~[jopt-simple-5.0.4.jar:?]
        at net.minecraft.server.Main.main(SourceFile:87) ~[server-1.20.4.jar:?]
        at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

Does anyone have an idea what might be the issue?

**Comment by itzg** [comment]
Wrong repo. I'll move this to the right place but you need to provide more information about what you tried. You're calling docker incorrectly but can't provide any advice without more info.
